### ISSUE TITLE
Folder "platform" name error

### ISSUE THREAD

**Issue by DieBieEngineering** [Jeroen6/QtKvaser#1]
First off, thanks for sharing this application. It will get me started even faster!

For this application to run on windows 7 I needed to change the folder "platform" to "platforms". Easy fix, but dont know the origin of the error, this however was the solution.

The exact qoute: "Application failed to start because it could not find or load the QT platform plugin “windows”"

**Comment by Jeroen6** [comment]
Yeah. It's always in those small details... When you've added Qt to path, these errors are easily made.
